[opa_risk_updater]
label = OPA Risk Score Updater
description = Converte risk_scores.csv in JSON per OPA
icon_path = appIcon.png
payload_format = json
param.opa_json_path = /opa_data/risk_scores.json
