# configs/mongodb/mongod.conf
#file di configurazione mongodb per crittografia TLS, formato JSON dei log degli audit pp

systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true

# Binding della rete interna, la direttiva bindIp permette la comunicazione all'interno della rete maritime-zta_backend
net:
  port: 27017
  bindIp: 0.0.0.0

# SEZIONE TLS, il database rifiuterà qualunque pacchetto di dati che non viaggi su un tunnel criptato e validato dai certificati digitali presenti nel volume /certs/
  # tls:
  #   mode: requireTLS
  #   certificateKeyFile: /certs/server.pem
  #   CAFile: /certs/ca.crt
  #   allowConnectionsWithoutCertificates: false

# Attivazione della sicurezza RBAC, ogni richiesta deve essere accompagnata da credenziali valide
security:
  authorization: enabled

