[http]
disabled = 0
port = 8088
enableSSL = 0

[http://maritime-hec]
disabled = 0
token = f34d1b82-628b-4b2a-8951-b8401314b875
index = main
sourcetype = _json

[monitor:///var/log/snort/alert_json.txt]
disabled = 0
index = main
sourcetype = snort_alert_json
crcSalt = <SOURCE>
