# Configura il monitoraggio Splunk dei log prodotti dai servizi di sicurezza.
[monitor:///var/log/snort/alert_json.txt]
disabled = 0
index = main
sourcetype = snort_alert_json
crcSalt = <SOURCE>

[monitor:///var/log/mongodb/mongod.log]
disabled = 0
index = main
sourcetype = mongodb_log
crcSalt = <SOURCE>

[monitor:///var/log/envoy/access.log]
disabled = 0
index = main
sourcetype = envoy_access_json
crcSalt = <SOURCE>
