# Interpreta correttamente il timestamp locale prodotto da Snort.
[snort_alert_json]
SHOULD_LINEMERGE = false
KV_MODE = json
TIME_PREFIX = \"timestamp\"\s*:\s*\"
TIME_FORMAT = %m/%d-%H:%M:%S.%6N
MAX_TIMESTAMP_LOOKAHEAD = 21
TZ = Europe/Rome
